[package]
name = "archman"
version = "0.1.0"
authors = ["Bartosz Wojno <bartoszwjn@gmail.com>"]
edition = "2018"
description = "A configuration utility for my specific Arch Linux setup"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
structopt = "0.3.21"
